project:
  type: website
  output-dir: C:\Users\gduan.stu\OneDrive - UBC\Documents\GitHub\E-Portfolio

website:
  title: "GuangLan Duan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: About Me
      - href: content.qmd
        text: Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

